### ISSUE TITLE
drawlsmask breaking with axis out of bounds error

### ISSUE THREAD

**Issue by AvlWx2014** [matplotlib/basemap#268]
drawlsmask uses numpy.concatenate to stick 1-D lon arrays together on axis 1. Starting in NumPy 1.10 concatenate will raise an error if `axis` kwarg does not exist already.

**Comment by micahcochran** [comment]
[Near the code in question](https://github.com/matplotlib/basemap/blob/master/lib/mpl_toolkits/basemap/__init__.py#L3960).

So you are saying that this line
```Python
lsmask_lons = np.concatenate((lsmask_lons,lsmask_lons[1:]+360),1)
```

Should be changed to this for NumPy 1.10:
```Python
lsmask_lons = np.concatenate((lsmask_lons,lsmask_lons[1:]+360),axis=1)
```

There are 4 other instances of np.concatenate in \__init\__.py

There currently isn't enough unit testing for geopandas to catch problems like this.

**Comment by AvlWx2014** [comment]
NumPy concatenate will raise an IndexError, starting in NumPy 1.10.0 if the axis given does not exist i.e. lsmask_lons.ndim < 2 and `axis` = 1

**Comment by WeatherGod** [comment]
I thought we already fixed these? Maybe not all of them needs changing:
https://github.com/matplotlib/basemap/pull/227

**Comment by AvlWx2014** [comment]
I read #211 and it sounds like exactly the same issue. Looking at the code in __init__ in the master, it appears the issue still exists in drawlsmask. In my fork I'm going to use numpy.hstack which will successfully do what we're looking for, but works in old and new versions of NumPy.
