### ISSUE TITLE
MPL2.1 deprecation warning for axesPatch

### ISSUE THREAD

**Issue by naught101** [matplotlib/basemap#382]
```py
/home/naught101/miniconda3/envs/science/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:1708: MatplotlibDeprecationWarning: The axesPatch function was deprecated in version 2.1. Use Axes.patch instead.
  limb = ax.axesPatch
/home/naught101/miniconda3/envs/science/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py:1711: MatplotlibDeprecationWarning: The axesPatch function was deprecated in version 2.1. Use Axes.patch instead.
  if limb is not ax.axesPatch:
```

**Comment by piercefreeman** [comment]
Seeing this same issue - anyone have advice on a solution?

**Comment by megies** [comment]
> Seeing this same issue - anyone have advice on a solution?

It's already fixed in master, see #373, so this is only about when a point release will be done.

**Comment by megies** [comment]
N.b. this will break basemap 1.1.0 with matplotlib 2.3 so a basemap point release is needed rather sooner than later, see https://github.com/matplotlib/matplotlib/commit/1279b841d52da5d93124b53f41274aced086f09c#diff-a7f4f21aa80e975d813bc436acb68d8cL1140.

**Comment by IndianaTones** [comment]
still not fixed? I tried everyone's advice and then some but the warning breaks my whole system!!

**Comment by WeatherGod** [comment]
Install basemap from conda-forge channel.

**Comment by WeatherGod** [comment]
Can you confirm that you are importing the correct version (v1.1.0)? You
might need to do a `conda update -c conda-forge basemap`

**Comment by WeatherGod** [comment]
```
>>> from mpl_toolkits import basemap
>>> basemap.__version__
'1.1.0'
```
What does it say for you?

**Comment by IndianaTones** [comment]
@megies @WeatherGod thank you for the help - clearly I am a newbie!  It's true, only warnings appear without errors but along with the warnings my entire system freezes and locks up with a re-start required.

**Comment by megies** [comment]
> along with the warnings my entire system freezes and locks up with a re-start required

Alright, but certainly that freeze is not related to this issue.

**Comment by IndianaTones** [comment]
well, it is this issue that triggers the warnings which is then followed by freezing, so somehow it is related.

**Comment by megies** [comment]
> well, it is this issue that triggers the warnings which is then followed by freezing, so somehow it is related.

It isn't, believe me. If you want to find out the problem, you should hop through your code line by line using a debugger. https://pymotw.com/3/pdb/index.html

But this is going way off-topic, here.

**Comment by Linux-cpp-lisp** [comment]
Can confirm that this warning still appears with the latest release ([v1.1.0](https://github.com/matplotlib/basemap/releases/tag/v1.1.0), installed today, from source, following the [documentation](https://matplotlib.org/basemap/users/installing.html)).

``
...lib/python3.5/site-packages/mpl_toolkits/basemap/__init__.py:1707: MatplotlibDeprecationWarning: The axesPatch function was deprecated in version 2.1. Use Axes.patch instead.
  if limb is not ax.axesPatch:
``

**Comment by WeatherGod** [comment]
yes, the fix was not in v1.1.0, but it is in master.

**Comment by megies** [comment]
> It locks up my whole system too...

I've said it before, a deprecation warning is not gonna freeze your system. You need to use a debugger to find out what command actually does not finish.
