### ISSUE TITLE
Function "addcyclic": IndexError

### ISSUE THREAD

**Issue by YixinNJU** [matplotlib/basemap#575]
Hi, I am using "addcyclic" function and encounter the Index Error. Error details are:

**IndexError**                                Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_11852/1134487354.py in <module>
      6 m.drawmeridians(np.arange(0.,360.,90.),linewidth=0.4,color='gray',labels=[True,True,True,True])
      7 #在Py3.7下使用basemap==1.2.0，在循环填白addcyclic时可能会报错
----> 8 psi_p1,lon1=addcyclic(np.array(psi_p),np.array(lon))
      9 lonsn, latsn = np.meshgrid(lon1, lat)
     10 x_cyc,y_cyc=m(lonsn,latsn) #建立投影坐标映射

D:\AnacondaSoftware\lib\site-packages\mpl_toolkits\basemap\__init__.py in addcyclic(*arr, **kwargs)
   5101         return _addcyclic_lon(arr[-1])
   5102     else:
-> 5103         return list(map(_addcyclic,arr[:-1])) + [_addcyclic_lon(arr[-1])]
   5104 
   5105 def _choosecorners(width,height,**kwargs):

D:\AnacondaSoftware\lib\site-packages\mpl_toolkits\basemap\__init__.py in _addcyclic(a)
   5086             raise ValueError('The specified axis does not correspond to an '
   5087                     'array dimension.')
-> 5088         return npsel.concatenate((a,a[slicer]),axis=axis)
   5089     def _addcyclic_lon(a):
   5090         """addcyclic function for a single longitude array"""

**IndexError**: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

The code is:
`psi_p1,lon1=addcyclic(np.array(psi_p),np.array(lon))`

Here is the variable _psi_p_: https://box.nju.edu.cn/f/64583aedd0c24eae909d/
_lon_: https://box.nju.edu.cn/f/a273d137b454468c8007/

Software and module versions are: Python 3.8.8, numpy 1.23.5,  basemap: 1.2.2

I am wondering whether it is due to inconsistency of package version? Is it possible to fix the bug without reinstall python or modules due to interdependence of a lot of my other modules. Thanks a lot!!

**Comment by molinav** [comment]
Hi @YixinNJU! This error sounds like #555, which was solved for `basemap` release 1.3.5. Can you try upgrading to the latest `basemap` version (currently 1.3.7)? The version 1.2.2 is a bit outdated. The version 1.3.7 is available at `conda-forge` for Windows x64 (presumably your OS and architecture).

**Comment by YixinNJU** [comment]
> 
Thank you for your reply! I upgraded `basemap` to 1.3.7 and re-import the module, the same Index Error still exists.

**Comment by YixinNJU** [comment]
> Hi @YixinNJU! This error sounds like #555, which was solved for `basemap` release 1.3.5. Can you try upgrading to the latest `basemap` version (currently 1.3.7)? The version 1.2.2 is a bit outdated. The version 1.3.7 is available at `conda-forge` for Windows x64 (presumably your OS and architecture).

Thank you for your reply! I upgraded basemap to 1.3.7 and re-import the module, the same Index Error still exists.
